version: '3.8'
services:
  nuxt:
    build: ./docker/next
    ports:
      - 3000:3000
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/sh -c "npm install && npm run dev"
