version: '3.8'
services:
  next:
    build: ./docker/next
    ports:
      - 3010:3010
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/sh -c "npm install && npm run dev"
